import React from "react";
import "./globals.css";
import "./style.css";
import "react-loading-skeleton/dist/skeleton.css";
import ReactQueryProvider from "./components/ReactQueryProvider";
import MaterialTailwind from "./components/MaterialTailwind";
import Header from "./components/header/Header";
import Search from "./components/search/Search";
import Footer from "./components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <MaterialTailwind>
        <html lang='en'>
          <body>
            <Header />
            <Search />
            {children}
            <Footer />
          </body>
        </html>
      </MaterialTailwind>
    </ReactQueryProvider>
  );
}
